// @generated
// This file is @generated by prost-build.
// ---------------------------------------------------------------------------
// Spawn launchpad data layer. One protobuf message per contract event.
// uint256/int256 wei amounts are decimal strings; addresses and hashes are
// 0x-prefixed lowercase hex strings; PoolId is the 0x-prefixed 32-byte hex.
// ---------------------------------------------------------------------------

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpawnEvents {
    /// MilestoneHook lifecycle
    #[prost(message, repeated, tag="1")]
    pub launches: ::prost::alloc::vec::Vec<Launch>,
    #[prost(message, repeated, tag="2")]
    pub graduations: ::prost::alloc::vec::Vec<Graduation>,
    #[prost(message, repeated, tag="3")]
    pub curve_deployments: ::prost::alloc::vec::Vec<CurveDeployment>,
    #[prost(message, repeated, tag="4")]
    pub band_deployments: ::prost::alloc::vec::Vec<BandDeployment>,
    #[prost(message, repeated, tag="5")]
    pub band_skips: ::prost::alloc::vec::Vec<BandSkip>,
    #[prost(message, repeated, tag="6")]
    pub milestone_harvests: ::prost::alloc::vec::Vec<MilestoneHarvest>,
    /// at most one per launch
    #[prost(message, optional, tag="7")]
    pub dev_buy: ::core::option::Option<DevBuy>,
    #[prost(message, optional, tag="8")]
    pub dev_buy_skip: ::core::option::Option<DevBuySkip>,
    /// Payout economics
    #[prost(message, repeated, tag="9")]
    pub payout_pot_fundings: ::prost::alloc::vec::Vec<PayoutPotFunding>,
    #[prost(message, repeated, tag="10")]
    pub payout_pot_redemptions: ::prost::alloc::vec::Vec<PayoutPotRedemption>,
    #[prost(message, repeated, tag="11")]
    pub payout_tips: ::prost::alloc::vec::Vec<PayoutTip>,
    #[prost(message, repeated, tag="12")]
    pub plugin_payouts: ::prost::alloc::vec::Vec<PluginPayout>,
    #[prost(message, repeated, tag="13")]
    pub creator_accruals: ::prost::alloc::vec::Vec<CreatorAccrual>,
    #[prost(message, repeated, tag="14")]
    pub creator_claims: ::prost::alloc::vec::Vec<CreatorClaim>,
    #[prost(message, repeated, tag="15")]
    pub creator_path_accruals: ::prost::alloc::vec::Vec<CreatorPathAccrual>,
    #[prost(message, repeated, tag="16")]
    pub creator_path_claims: ::prost::alloc::vec::Vec<CreatorPathClaim>,
    #[prost(message, repeated, tag="17")]
    pub creator_path_claim_failures: ::prost::alloc::vec::Vec<CreatorPathClaimFailure>,
    #[prost(message, repeated, tag="18")]
    pub protocol_accruals: ::prost::alloc::vec::Vec<ProtocolAccrual>,
    #[prost(message, repeated, tag="19")]
    pub protocol_claims: ::prost::alloc::vec::Vec<ProtocolClaim>,
    #[prost(message, repeated, tag="20")]
    pub fee_collections: ::prost::alloc::vec::Vec<FeeCollection>,
    #[prost(message, repeated, tag="21")]
    pub fee_routings: ::prost::alloc::vec::Vec<FeeRouting>,
    /// Governance / registry
    #[prost(message, repeated, tag="22")]
    pub economic_configs: ::prost::alloc::vec::Vec<EconomicConfigSet>,
    #[prost(message, repeated, tag="23")]
    pub protocol_recipient_sets: ::prost::alloc::vec::Vec<ProtocolRecipientSet>,
    #[prost(message, repeated, tag="24")]
    pub plugin_registrations: ::prost::alloc::vec::Vec<PluginRegistration>,
    #[prost(message, repeated, tag="25")]
    pub plugin_suspensions: ::prost::alloc::vec::Vec<PluginSuspension>,
    #[prost(message, repeated, tag="26")]
    pub minter_sets: ::prost::alloc::vec::Vec<MinterSet>,
    /// Launch token (dynamic data source resolved via store_pools)
    #[prost(message, repeated, tag="27")]
    pub token_burns: ::prost::alloc::vec::Vec<TokenBurn>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradedSwaps {
    #[prost(message, repeated, tag="1")]
    pub swaps: ::prost::alloc::vec::Vec<TradedSwap>,
}
/// --- Common per-event context ---------------------------------------------
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventMeta {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub block_hash: ::prost::alloc::string::String,
    /// block unix seconds
    #[prost(uint64, tag="3")]
    pub timestamp: u64,
    #[prost(string, tag="4")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="5")]
    pub log_index: u32,
    /// block:log_index, unique per event instance
    #[prost(string, tag="6")]
    pub ordinal_key: ::prost::alloc::string::String,
}
// --- MilestoneHook lifecycle ----------------------------------------------

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Launch {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    /// 0x + 32-byte hex
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub creator: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub token: ::prost::alloc::string::String,
    /// uint256 decimal string
    #[prost(string, tag="5")]
    pub total_supply: ::prost::alloc::string::String,
    /// int24
    #[prost(int32, tag="6")]
    pub opening_level: i32,
    #[prost(int32, tag="7")]
    pub far_level: i32,
    /// 0x + 32-byte hex
    #[prost(string, tag="8")]
    pub config_hash: ::prost::alloc::string::String,
    /// LaunchConfigured bitmask, decimal string
    #[prost(string, tag="9")]
    pub payout_plan: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub dev_buy_share_wad: ::prost::alloc::string::String,
    /// v4 pool key components for cross-referencing PoolManager data
    #[prost(string, tag="11")]
    pub hook: ::prost::alloc::string::String,
    /// always ETH address (0x0)
    #[prost(string, tag="12")]
    pub currency0: ::prost::alloc::string::String,
    /// launch token
    #[prost(string, tag="13")]
    pub currency1: ::prost::alloc::string::String,
    /// token metadata, fetched once per token via cached RPC (store_token_meta)
    #[prost(string, tag="14")]
    pub token_name: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub token_symbol: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub token_decimals: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Graduation {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub graduation_level: i32,
    #[prost(string, tag="4")]
    pub quote_proceeds: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub lp_seed_quote: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub creator_quote: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub protocol_quote: ::prost::alloc::string::String,
    /// uint128 decimal string
    #[prost(string, tag="8")]
    pub full_range_liquidity: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CurveDeployment {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub minted: ::prost::alloc::string::String,
    /// full bitmap after mint
    #[prost(uint32, tag="4")]
    pub deployed: u32,
    #[prost(string, tag="5")]
    pub token_settled: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BandDeployment {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub index: u32,
    #[prost(int32, tag="4")]
    pub level_lower: i32,
    #[prost(int32, tag="5")]
    pub level_upper: i32,
    /// uint128 decimal string
    #[prost(string, tag="6")]
    pub liquidity: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub token_inventory: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BandSkip {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub index: u32,
    #[prost(string, tag="4")]
    pub carried_inventory: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MilestoneHarvest {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub index: u32,
    #[prost(string, tag="4")]
    pub quote_proceeds: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub token_residue: ::prost::alloc::string::String,
    #[prost(uint32, tag="6")]
    pub completed_milestones: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DevBuy {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub tokens_bought: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub eth_spent: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DevBuySkip {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub relayer: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub tokens_requested: ::prost::alloc::string::String,
}
// --- Payout economics ------------------------------------------------------

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayoutPotFunding {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub milestone_index: u32,
    #[prost(string, tag="4")]
    pub gross_quote: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub service_fee: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub net_quote: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub economic_version: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayoutPotRedemption {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayoutTip {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub flusher: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PluginPayout {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub plugin_index: u32,
    #[prost(string, tag="4")]
    pub plugin: ::prost::alloc::string::String,
    /// DELIVERED | CARRIED | REDIRECTED
    #[prost(enumeration="PluginOutcome", tag="5")]
    pub outcome: i32,
    #[prost(string, tag="6")]
    pub current_share: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub previous_carry: ::prost::alloc::string::String,
    /// delivered / carried / redirected respectively
    #[prost(string, tag="8")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatorAccrual {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(enumeration="AccrualSource", tag="4")]
    pub source: i32,
    #[prost(uint64, tag="5")]
    pub economic_version: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatorClaim {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub holder: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatorPathAccrual {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatorPathClaim {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub holder: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatorPathClaimFailure {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub holder: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtocolAccrual {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    /// zero-pool-id sentinel for global accruals if any
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(enumeration="AccrualSource", tag="4")]
    pub source: i32,
    #[prost(uint64, tag="5")]
    pub economic_version: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtocolClaim {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub recipient: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeCollection {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub caller: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub quote_fees: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub token_fees: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeRouting {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub creator_quote: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub protocol_quote: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub diverted_to_next_band: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub tokens_burned: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub economic_version: u64,
}
// --- Governance / registry -------------------------------------------------

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EconomicConfigSet {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(uint64, tag="2")]
    pub version: u64,
    #[prost(string, tag="3")]
    pub harvest_service_fee_wad: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub quote_creator_share_wad: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub token_milestone_fund_share_wad: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtocolRecipientSet {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub recipient: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PluginRegistration {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(uint32, tag="2")]
    pub registry_index: u32,
    #[prost(string, tag="3")]
    pub plugin: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub take_wad: ::prost::alloc::string::String,
    #[prost(uint32, tag="5")]
    pub gas_limit: u32,
    #[prost(string, tag="6")]
    pub code_hash: ::prost::alloc::string::String,
    /// PluginRole enum value
    #[prost(uint32, tag="7")]
    pub role: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PluginSuspension {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(uint32, tag="2")]
    pub registry_index: u32,
    #[prost(bool, tag="3")]
    pub suspended: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MinterSet {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub minter: ::prost::alloc::string::String,
}
// --- Launch token ----------------------------------------------------------

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenBurn {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub token: ::prost::alloc::string::String,
    /// from-address of the Transfer-to-zero
    #[prost(string, tag="3")]
    pub burner: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub amount: ::prost::alloc::string::String,
}
// --- Uniswap v4 swaps (PoolManager singleton) -------------------------------

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradedSwap {
    #[prost(message, optional, tag="1")]
    pub meta: ::core::option::Option<EventMeta>,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    /// resolved from store_pools
    #[prost(string, tag="3")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub sender: ::prost::alloc::string::String,
    /// amount0 < 0 (ETH in, token out)
    #[prost(bool, tag="5")]
    pub is_buy: bool,
    /// int256 |amount0| as decimal string (wei)
    #[prost(string, tag="6")]
    pub amount0_eth: ::prost::alloc::string::String,
    /// int256 |amount1| as decimal string (wei)
    #[prost(string, tag="7")]
    pub amount1_tokens: ::prost::alloc::string::String,
    /// uint160 decimal string
    #[prost(string, tag="8")]
    pub sqrt_price_x96: ::prost::alloc::string::String,
    /// uint128 decimal string
    #[prost(string, tag="9")]
    pub liquidity: ::prost::alloc::string::String,
    #[prost(int32, tag="10")]
    pub tick: i32,
    /// hundredths of a bip, e.g. 100 = 1%
    #[prost(uint32, tag="11")]
    pub fee: u32,
    /// realized fee taken by the pool on this swap (fee/1e6 of input side)
    ///
    /// wei, 0 when input was tokens
    #[prost(string, tag="12")]
    pub fee_eth: ::prost::alloc::string::String,
    /// wei, 0 when input was ETH
    #[prost(string, tag="13")]
    pub fee_tokens: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PluginOutcome {
    PluginDelivered = 0,
    PluginCarried = 1,
    PluginRedirected = 2,
}
impl PluginOutcome {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            PluginOutcome::PluginDelivered => "PLUGIN_DELIVERED",
            PluginOutcome::PluginCarried => "PLUGIN_CARRIED",
            PluginOutcome::PluginRedirected => "PLUGIN_REDIRECTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PLUGIN_DELIVERED" => Some(Self::PluginDelivered),
            "PLUGIN_CARRIED" => Some(Self::PluginCarried),
            "PLUGIN_REDIRECTED" => Some(Self::PluginRedirected),
            _ => None,
        }
    }
}
/// Mirrors MilestoneBase.AccrualSource (CURVE_PROCEEDS=0, SWAP_FEES=1, MILESTONE_HARVEST=2)
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AccrualSource {
    CurveProceeds = 0,
    SwapFees = 1,
    MilestoneHarvest = 2,
}
impl AccrualSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            AccrualSource::CurveProceeds => "CURVE_PROCEEDS",
            AccrualSource::SwapFees => "SWAP_FEES",
            AccrualSource::MilestoneHarvest => "MILESTONE_HARVEST",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CURVE_PROCEEDS" => Some(Self::CurveProceeds),
            "SWAP_FEES" => Some(Self::SwapFees),
            "MILESTONE_HARVEST" => Some(Self::MilestoneHarvest),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
